WARNING: The directory '/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Defaulting to user installation because normal site-packages is not writeable
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fdc8f53c370>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/jiwer/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fdc8f53c580>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/jiwer/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fdc8f53c760>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/jiwer/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fdc8f53c910>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/jiwer/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fdc8f53cac0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/jiwer/
ERROR: Could not find a version that satisfies the requirement jiwer (from versions: none)
ERROR: No matching distribution found for jiwer
